### ISSUE TITLE
Cannot be imported server side

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [carrymisss/react-day-and-night-toggle#1]
**Describe the bug**
I'm using next.js, so internally it is trying to `require('react-day-and-night-toggle')`, which doesn't work, because this uses `import` statements.

**To Reproduce**
1. Install this package
2. Run `node -e "require('react-day-and-night-toggle')"`
3. See error

Repl with minimum code: https://replit.com/@Programmerraj/react-day-and-night-toggle-bug#index.js

**Expected behavior**
It should be able to be `require`d in Node.js.

**Comment by carrymisss** [comment]
It was fixed in 1.0.16.
Please update.
